import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import TranstackQueryProvider from "@/components/TranstackQueryProvider";
import { Toaster } from "react-hot-toast";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "MYSHOPBD-HABIB",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className + ' dark:bg-black text-white container mx-auto sm:p-0 px-4'}>
                <Toaster
                    position="top-center"
                    reverseOrder={false}
                />
                <TranstackQueryProvider>
                    <Header />
                    <main>
                        {children}
                    </main>
                    <Footer />
                </TranstackQueryProvider>
            </body>
        </html>
    );
}
