import Error from "@/components/Error";
import ProductNotFound from "@/components/Product-not-found";
import { delay } from "@/utils";
import { Metadata } from "next";
import dynamic from "next/dynamic";
import { redirect } from "next/navigation";
export const metadata: Metadata = {
    title: "SEARCH - MYSHOPBD",
    description: "Generated by create next app",
};
const SearchResult = dynamic(() => import("@/components/RenderSearchResult"), {
    ssr: true,
});

const SearchPage = async ({ searchParams }: { searchParams: any }) => {
    if (!searchParams.q) {
        redirect("/");
    }

    const fetchProductByQuery = async (q: string) => {
        try {
            let res = await fetch(`https://dummyjson.com/products/search?q=${q}`);
            let data = await res.json()
            return data.products
        } catch (error) {
            console.log("fd");

            return {
                error: true,
                message: "Failed to  fetch products"
            }
        }
    }


    let data = await fetchProductByQuery(searchParams.q || "");


    if (data.error) {
        return <Error />
    }

    if (data.length === 0) {
        return <ProductNotFound />;
    }

    return (
        <section className="w-full">
            <div className="py-6">
                <p className="font-bold text-zinc-400">
                    YOUR FOLLOWING SEARCH RESULT{" "}
                    <span className="text-blue-800 uppercase">{`"${searchParams.q}"`}</span>
                </p>
            </div>
            <SearchResult products={data} />
        </section>
    );
};

export default SearchPage;
