import ProductItem from "@/components/productItem";
import { Metadata } from "next";
import Link from "next/link";
import React from "react";
export const metadata: Metadata = {
    title: "PRODUCT-LISTS",
    description: "Generated by create next app",
};
const ProductLists = () => {
    return (
        <section className="w-full px-4 ">
            <div className="flex items-center p-4 justify-between w-full"><span>All Porduct</span> <Link href="/dashboard/add-new-product" className="p-2 bg-blue-700 text-white rounded-md">Add New Product</Link></div>
            <div className="  flex flex-1 flex-col w-full   mt-5 rounded-md">
                {/* wrapper  */}

                <div className="grid grid-cols-12 ">
                    <div className="col-span-6 text-center pb-3">
                        <span className="font-semibold">NAME</span>
                    </div>
                    <div className="col-span-2  text-center">
                        <span className="font-semibold">PRICE</span>
                    </div>
                    <div className="col-span-2  text-center">
                        <span className="font-semibold">CATEGORY</span>
                    </div>
                    <div className="col-span-2  text-center">
                        <span className="font-semibold">BRAND</span>
                    </div>
                </div>
                <ProductItem />
                {/* <ProductItem />
                <ProductItem />
                <ProductItem />
                <ProductItem />
                <ProductItem /> */}
            </div>


        </section>
    );
};

export default ProductLists;
