import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { Toaster } from "react-hot-toast";
import { GoogleOAuthProvider } from "@react-oauth/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AUTHENTICTION | MYSHOPBD",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + "bg-black"}>
        <Toaster position="top-center" reverseOrder={false} />

        <GoogleOAuthProvider clientId={process.env.GOOGLECLIENTID!}>
          {children}
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
